### ISSUE TITLE
How does one calibrate with esphome?

### ISSUE THREAD

**Issue by olskar** [alsFC/esphome-iSpindel#1]
Hello!

How does one calibrate with esphome?
In original version i understand you set the values somehow?

**Comment by alsFC** [comment]
Hi!
I used the Online Calibration Tool referenced in iSpindel documentation: https://www.ispindel.de/tools/calibration/calibration.htm

I followed the steps of "Variante A" described in iSpindel documentation: https://www.ispindel.de/docs/Kalibrierung.html

With the resulting 3rd degree function I configured a template sensor in HA as you can see in sensors.yaml: https://github.com/alsFC/esphome-iSpindel/blob/main/sensors.yaml
